#pragma once

#define PHX_MOUSE_BUTTON_1         0
#define PHX_MOUSE_BUTTON_2         1
#define PHX_MOUSE_BUTTON_3         2
#define PHX_MOUSE_BUTTON_4         3
#define PHX_MOUSE_BUTTON_5         4
#define PHX_MOUSE_BUTTON_6         5
#define PHX_MOUSE_BUTTON_7         6
#define PHX_MOUSE_BUTTON_8         7
#define PHX_MOUSE_BUTTON_LAST      PHX_MOUSE_BUTTON_8
#define PHX_MOUSE_BUTTON_LEFT      PHX_MOUSE_BUTTON_1
#define PHX_MOUSE_BUTTON_RIGHT     PHX_MOUSE_BUTTON_2
#define PHX_MOUSE_BUTTON_MIDDLE    PHX_MOUSE_BUTTON_3